// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booking.sql

package db

import (
	"context"
	"time"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (restaurant_id, table_id, user_id, date, time_from, time_to, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
RETURNING id, restaurant_id, table_id, user_id, date, time_from, time_to, status, created_at, updated_at
`

type CreateBookingParams struct {
	RestaurantID int64     `json:"restaurant_id"`
	TableID      int64     `json:"table_id"`
	UserID       int64     `json:"user_id"`
	Date         time.Time `json:"date"`
	TimeFrom     time.Time `json:"time_from"`
	TimeTo       time.Time `json:"time_to"`
	Status       string    `json:"status"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.RestaurantID,
		arg.TableID,
		arg.UserID,
		arg.Date,
		arg.TimeFrom,
		arg.TimeTo,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.TableID,
		&i.UserID,
		&i.Date,
		&i.TimeFrom,
		&i.TimeTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings
WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBooking, id)
	return err
}

const getAllBookings = `-- name: GetAllBookings :many
SELECT id, restaurant_id, table_id, user_id, date, time_from, time_to, status, created_at, updated_at
FROM bookings
ORDER BY date, time_from
`

func (q *Queries) GetAllBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, getAllBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.TableID,
			&i.UserID,
			&i.Date,
			&i.TimeFrom,
			&i.TimeTo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, restaurant_id, table_id, user_id, date, time_from, time_to, status, created_at, updated_at
FROM bookings
WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.TableID,
		&i.UserID,
		&i.Date,
		&i.TimeFrom,
		&i.TimeTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings
SET restaurant_id = $2,
    table_id = $3,
    user_id = $4,
    date = $5,
    time_from = $6,
    time_to = $7,
    status = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, restaurant_id, table_id, user_id, date, time_from, time_to, status, created_at, updated_at
`

type UpdateBookingParams struct {
	ID           int64     `json:"id"`
	RestaurantID int64     `json:"restaurant_id"`
	TableID      int64     `json:"table_id"`
	UserID       int64     `json:"user_id"`
	Date         time.Time `json:"date"`
	TimeFrom     time.Time `json:"time_from"`
	TimeTo       time.Time `json:"time_to"`
	Status       string    `json:"status"`
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBooking,
		arg.ID,
		arg.RestaurantID,
		arg.TableID,
		arg.UserID,
		arg.Date,
		arg.TimeFrom,
		arg.TimeTo,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.TableID,
		&i.UserID,
		&i.Date,
		&i.TimeFrom,
		&i.TimeTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
