// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Booking struct {
	ID           int64     `json:"id"`
	RestaurantID int64     `json:"restaurant_id"`
	TableID      int64     `json:"table_id"`
	UserID       int64     `json:"user_id"`
	Date         time.Time `json:"date"`
	TimeFrom     time.Time `json:"time_from"`
	TimeTo       time.Time `json:"time_to"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Restaurant struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Address     sql.NullString `json:"address"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Status      bool           `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Table struct {
	ID           int64     `json:"id"`
	RestaurantID int64     `json:"restaurant_id"`
	TableNumber  string    `json:"table_number"`
	Seats        int32     `json:"seats"`
	Status       bool      `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type User struct {
	ID          int64          `json:"id"`
	Name        sql.NullString `json:"name"`
	Email       sql.NullString `json:"email"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Role        sql.NullString `json:"role"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}
