// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBooking(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAllBookings(ctx context.Context) ([]Booking, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetBookingByID(ctx context.Context, id int64) (Booking, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
