// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restaurant.sql

package db

import (
	"context"
	"database/sql"
)

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (name, address, phone_number, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, name, address, phone_number, status, created_at, updated_at
`

type CreateRestaurantParams struct {
	Name        string         `json:"name"`
	Address     sql.NullString `json:"address"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Status      bool           `json:"status"`
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, createRestaurant,
		arg.Name,
		arg.Address,
		arg.PhoneNumber,
		arg.Status,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRestaurnat = `-- name: DeleteRestaurnat :exec
DELETE FROM restaurants
WHERE id = $1
`

func (q *Queries) DeleteRestaurnat(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRestaurnat, id)
	return err
}

const getAllRestaurnats = `-- name: GetAllRestaurnats :many
SELECT id, name, address, phone_number, status, created_at, updated_at FROM restaurants
ORDER BY id
`

func (q *Queries) GetAllRestaurnats(ctx context.Context) ([]Restaurant, error) {
	rows, err := q.db.QueryContext(ctx, getAllRestaurnats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Restaurant
	for rows.Next() {
		var i Restaurant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.PhoneNumber,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurnatByID = `-- name: GetRestaurnatByID :one
SELECT id, name, address, phone_number, status, created_at, updated_at FROM restaurants
WHERE id = $1
`

func (q *Queries) GetRestaurnatByID(ctx context.Context, id int64) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, getRestaurnatByID, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRestaurnat = `-- name: UpdateRestaurnat :one
UPDATE restaurants
SET name = $2,
    address = $3,
    phone_number = $4,
    status = $5,
    updated_at = now()
Where id = $1
RETURNING id, name, address, phone_number, status, created_at, updated_at
`

type UpdateRestaurnatParams struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Address     sql.NullString `json:"address"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Status      bool           `json:"status"`
}

func (q *Queries) UpdateRestaurnat(ctx context.Context, arg UpdateRestaurnatParams) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, updateRestaurnat,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.PhoneNumber,
		arg.Status,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
