// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: table.sql

package db

import (
	"context"
)

const createTable = `-- name: CreateTable :one
INSERT INTO tables (restaurant_id, table_number, seats, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, restaurant_id, table_number, seats, status, created_at, updated_at
`

type CreateTableParams struct {
	RestaurantID int64  `json:"restaurant_id"`
	TableNumber  string `json:"table_number"`
	Seats        int32  `json:"seats"`
	Status       bool   `json:"status"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, createTable,
		arg.RestaurantID,
		arg.TableNumber,
		arg.Seats,
		arg.Status,
	)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.TableNumber,
		&i.Seats,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTable = `-- name: DeleteTable :exec
DELETE FROM tables
WHERE id = $1
`

func (q *Queries) DeleteTable(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTable, id)
	return err
}

const getAllTables = `-- name: GetAllTables :many
SELECT id, restaurant_id, table_number, seats, status, created_at, updated_at FROM tables
ORDER BY id
`

func (q *Queries) GetAllTables(ctx context.Context) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, getAllTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Table
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.TableNumber,
			&i.Seats,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableByID = `-- name: GetTableByID :one
SELECT id, restaurant_id, table_number, seats, status, created_at, updated_at FROM tables 
WHERE id = $1
`

func (q *Queries) GetTableByID(ctx context.Context, id int64) (Table, error) {
	row := q.db.QueryRowContext(ctx, getTableByID, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.TableNumber,
		&i.Seats,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTable = `-- name: UpdateTable :one
UPDATE tables
SET restaurant_id = $2,
    table_number = $3,
    seats = $4,
    status = $5,
    updated_at = now()
Where id = $1
RETURNING id, restaurant_id, table_number, seats, status, created_at, updated_at
`

type UpdateTableParams struct {
	ID           int64  `json:"id"`
	RestaurantID int64  `json:"restaurant_id"`
	TableNumber  string `json:"table_number"`
	Seats        int32  `json:"seats"`
	Status       bool   `json:"status"`
}

func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, updateTable,
		arg.ID,
		arg.RestaurantID,
		arg.TableNumber,
		arg.Seats,
		arg.Status,
	)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.TableNumber,
		&i.Seats,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
